### ISSUE TITLE
Cannot move EQ Sliders. Windows 10

### ISSUE THREAD

**Issue by nemesys23** [gmallios/SoundcoreManager#102]
Cannot move EQ sliders at all in Windows 10.  Tested using Liberty Air 2 Pro's and Souncore Life Q30.  EQ had different appearance with each device.  This is my first report on Github so forgive me if I am doing this wrong.

![souncore1](https://github.com/gmallios/SoundcoreManager/assets/135839778/e0358109-da5c-4c68-81a8-bc52cf778931)
![souncore2](https://github.com/gmallios/SoundcoreManager/assets/135839778/169d350a-52fb-4010-9e96-0d3e1cc9bf45)

**Comment by gmallios** [comment]
Hmm, if you hover over one dot does its value pop-up? The dots should be draggable vertically.

**Comment by el3ctrician** [comment]
Same issue here, the value does pop-up but the dots are not draggable. The mouse pointer turns to a hand but can't move any pointer for liberty air 2 pro

**Comment by deaconb** [comment]
Confirming same issue for Life A2 NC... EQ values popup on hover, cursor changes to hand, but unable to drag points.

**Comment by deaconb** [comment]
Fix confirmed on Life A2 NC ... thanks.
