### ISSUE TITLE
Response Checksum Error Soundcore Liberty Air 2 Pro

### ISSUE THREAD

**Issue by oanamateiflorin** [gmallios/SoundcoreManager#21]
After choosing to connect to Soundcore Libery Air 2 Pro the screen is loading forever and in the console I get a lot of checksum errors
[tauri.localhost-1680858911042.log](https://github.com/gmallios/SoundcoreManager/files/11177768/tauri.localhost-1680858911042.log)

**Comment by gmallios** [comment]
Weird, I use Liberty Air 2 Pros and i see the occasional checksum error but not it's not continuous. Any specific conditions that this happens?

**Comment by gmallios** [comment]
I managed to replicate this issue and pushed a new build which disables checksum validation until i get that sorted out.

**Comment by oanamateiflorin** [comment]
> Weird, I use Liberty Air 2 Pros and i see the occasional checksum error but not it's not continuous. Any specific conditions that this happens?

I don't really know if there are any specific conditions why this could happen. I tried the new build and now it's working. Thank you very much for your help!
